[package]
name = "cross-toolchain-override-bug"
version = "0.1.0"
authors = ["kay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
